-- LeetCode #610: Triangle Judgement
-- Difficulty: Easy
--
-- Problem:
-- Report for every three line segments whether they can form a triangle.
--
--   "Leaf": if the node is a leaf node.
--   "Root": if the node is the root of the tree.
--   "Inner": If the node is neither a leaf node nor a root node.
--   Write a solution to report the type of each node in the tree.
--
-- Approach:
-- Self join , Case , IS NULL , IS NOT NULL 
-- 
-- Pattern:
-- SELF JOIN and CASE
--
-- Solution:
