-- LeetCode #1251: Average Selling Price
-- Difficulty: Easy
--
-- Problem:
-- Write a solution to find the average selling price for each product. 
-- average_price should be rounded to 2 decimal places. If a product does not have any sold units, its average selling price is assumed to be 0.
--
--
-- Approach:
--
--
--
-- Pattern: 
--
--
--
-- Solution:
